In [159]:
import pandas as pd 
import numpy as np

In [160]:
df = pd.read_csv('/Users/13630/Downloads/stancedetection-main/dataset_stance.csv')

In [161]:
pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))) - skipping
Note: you may need to restart the kernel to use updated packages.


In [162]:
import sklearn

In [163]:
from sklearn.feature_extraction.text import CountVectorizer

In [164]:
#no separation based on subtopic
df_for = []
df_against = []
df_neutral = []
for k in range(len(df)):
    if df['Stance'][k] == 'FAVOR':
        df_for.append(str(x) for x in df['Tweet'][k]) 
    elif df['Stance'][k] == 'AGAINST':
        df_against.append(str(x) for x in df['Tweet'][k])
    else:
        df_neutral.append(str(x) for x in df['Tweet'][k])

In [165]:
df.Target.value_counts()

Hillary Clinton                     984
Feminist Movement                   949
Legalization of Abortion            933
Atheism                             733
Donald Trump                        707
Climate Change is a Real Concern    564
Name: Target, dtype: int64

# Donald Trump

In [166]:
target = 'Donald Trump'
df_target = df[df.Target == target]

In [167]:
#Stance
target = 'Donald Trump'
df_target = df[df.Target == target]
df_favor = df_target[df_target.Stance == 'FAVOR']
df_none = df_target[df_target.Stance == 'NONE']
df_against = df_target[df_target.Stance == 'AGAINST']

df_target

Unnamed: 0                                              Tweet  \
4163        1249  @2014voteblue @ChrisJZullo blindly supporting ...   
4164        1250  @ThePimpernelX @Cameron_Gray @CalebHowe  Total...   
4165        1251  @JeffYoung @ThePatriot143 I fully support full...   
4166        1252  @ABC Stupid is as stupid does! Showedhis true ...   
4167        1253  @HouseGOP we now have one political party. The...   
...          ...                                                ...   
4865        1951  @realDonaldTrump we all want you as the next p...   
4866        1952  @RSherman_25 Join Twitter Trump brigade #oneth...   
4867        1953  @JoeyBats19 Join Twitter Trump brigade #onetho...   
4868        1954  Trump's outlandish statements is political str...   
4869        1955  @RMConservative @DagnyRed ,P.C. is out of cont...   

            Target   Stance  \
4163  Donald Trump     NONE   
4164  Donald Trump     NONE   
4165  Donald Trump     NONE   
4166  Donald Trump  AGAINST   
4167  Donald Trump     NONE   
...            ...      ...   
4865  Donald Trump    FAVOR   
4866  Donald Trump    FAVOR   
4867  Donald Trump    FAVOR   
4868  Donald Trump  AGAINST   
4869  Donald Trump     NONE   

                                        Opinion Towards Sentiment  
4163  2. The tweet does NOT expresses opinion about ...       neg  
4164  2. The tweet does NOT expresses opinion about ...       pos  
4165  2. The tweet does NOT expresses opinion about ...       pos  
4166  1.  The tweet explicitly expresses opinion abo...       neg  
4167  2. The tweet does NOT expresses opinion about ...       neg  
...                                                 ...       ...  
4865  1.  The tweet explicitly expresses opinion abo...       pos  
4866  1.  The tweet explicitly expresses opinion abo...       pos  
4867  1.  The tweet explicitly expresses opinion abo...       pos  
4868  1.  The tweet explicitly expresses opinion abo...       neg  
4869  2. The tweet does NOT expresses opinion about ...       neg  

[707 rows x 6 columns]

In [168]:
df_target = df_target.drop('Unnamed: 0', axis='columns')
df_target = df_target.reset_index()
df_target = df_target.drop('index', axis='columns')

df_target

Tweet        Target   Stance  \
0    @2014voteblue @ChrisJZullo blindly supporting ...  Donald Trump     NONE   
1    @ThePimpernelX @Cameron_Gray @CalebHowe  Total...  Donald Trump     NONE   
2    @JeffYoung @ThePatriot143 I fully support full...  Donald Trump     NONE   
3    @ABC Stupid is as stupid does! Showedhis true ...  Donald Trump  AGAINST   
4    @HouseGOP we now have one political party. The...  Donald Trump     NONE   
..                                                 ...           ...      ...   
702  @realDonaldTrump we all want you as the next p...  Donald Trump    FAVOR   
703  @RSherman_25 Join Twitter Trump brigade #oneth...  Donald Trump    FAVOR   
704  @JoeyBats19 Join Twitter Trump brigade #onetho...  Donald Trump    FAVOR   
705  Trump's outlandish statements is political str...  Donald Trump  AGAINST   
706  @RMConservative @DagnyRed ,P.C. is out of cont...  Donald Trump     NONE   

                                       Opinion Towards Sentiment  
0    2. The tweet does NOT expresses opinion about ...       neg  
1    2. The tweet does NOT expresses opinion about ...       pos  
2    2. The tweet does NOT expresses opinion about ...       pos  
3    1.  The tweet explicitly expresses opinion abo...       neg  
4    2. The tweet does NOT expresses opinion about ...       neg  
..                                                 ...       ...  
702  1.  The tweet explicitly expresses opinion abo...       pos  
703  1.  The tweet explicitly expresses opinion abo...       pos  
704  1.  The tweet explicitly expresses opinion abo...       pos  
705  1.  The tweet explicitly expresses opinion abo...       neg  
706  2. The tweet does NOT expresses opinion about ...       neg  

[707 rows x 5 columns]

In [169]:
list_of_donald_tweets = []
for t in range(len(df_target)):
    list_of_donald_tweets.append(df_target['Tweet'][t])
list_of_donald_tweets

['@2014voteblue @ChrisJZullo blindly supporting political parties is willfull ignorance, repub or dem. #SemST',
 '@ThePimpernelX @Cameron_Gray @CalebHowe  Totally agree ...time to get out of the Twitter Peanut Gallery and take "arms #SemST',
 '@JeffYoung @ThePatriot143 I fully support full repeal. I will work for candidates who I believe will make it happen! #SemST',
 '@ABC Stupid is as stupid does! Showedhis true colors; seems that he ignores that US was invaded, & plundered,not discovered #SemST',
 "@HouseGOP we now have one political party. The Socialist party. No more BS. We don't believe you anymore. #SemST",
 "Donald Trump isn't afraid to roast everyone. #SemST",
 'Donald Trump for president? I can dig it.  #SemST',
 'nothing about obamacare changed today what changed is the total exposure of anti-constitutional terrorism at the supremecourt #SemST',
 'I have one friend, he said he has more accountants than he has nurses. #SemST',
 'After today SCOTUS has passed more legislation 

In [170]:
#labels for donald trump df
list_of_labels = []
for t in range(707):
    if df_target['Stance'][t] == 'FAVOR':
        list_of_labels.append(1)
    elif df_target['Stance'][t] == 'AGAINST':
        list_of_labels.append(2)
    else:
        list_of_labels.append(0) 

In [171]:
list_of_labels

[0,
 0,
 0,
 2,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 2,
 0,
 2,
 0,
 2,
 0,
 2,
 1,
 0,
 2,
 0,
 0,
 2,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 2,
 2,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 2,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 2,
 2,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 2,
 1,
 0,
 0,
 1,
 0,
 0,
 2,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 2,
 2,
 2,
 2,
 2,
 0,
 2,
 0,
 1,
 2,
 1,
 1,
 2,
 1,
 0,
 0,
 2,
 2,
 2,
 1,
 2,
 0,
 2,
 2,
 1,
 0,
 1,
 2,
 0,
 0,
 0,
 2,
 1,
 0,
 0,
 2,
 2,
 0,
 2,
 0,
 0,
 0,
 1,
 2,
 0,
 1,
 0,
 2,
 0,
 2,
 2,
 1,
 0,
 2,
 0,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,


In [172]:
pip install nltk

Defaulting to user installation because normal site-packages is not writeable
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))) - skipping
Note: you may need to restart the kernel to use updated packages.


In [173]:
import nltk

In [174]:
nltk.download('averaged_perceptron_tagger')

[nltk_data] Error loading averaged_perceptron_tagger: HTTP Error 401:
[nltk_data]     Unauthorized


False

In [175]:
# WORDNET LEMMATIZER (with appropriate pos tags)

from nltk.stem import WordNetLemmatizer
#nltk.download('averaged_perceptron_tagger')
from nltk.corpus import wordnet
from nltk.corpus import stopwords

nltk.download('stopwords')

[nltk_data] Error loading stopwords: HTTP Error 401: Unauthorized


False

In [176]:
lemmatizer = WordNetLemmatizer()
 
# Define function to lemmatize each word with its POS tag
 
# POS_TAGGER_FUNCTION : TYPE 1
def pos_tagger(nltk_tag):
    if nltk_tag.startswith('J'):
        return wordnet.ADJ
    elif nltk_tag.startswith('V'):
        return wordnet.VERB
    elif nltk_tag.startswith('N'):
        return wordnet.NOUN
    elif nltk_tag.startswith('R'):
        return wordnet.ADV
    else:         
        return None
 
def lemmatizing(data):
    lemmatized_data = []
    for i in range(len(data)):
        sentence = data[i]

        # tokenize the sentence and find the POS tag for each token
        word_tokens = nltk.wordpunct_tokenize(sentence)
 
        pos_tagged = nltk.pos_tag(word_tokens) 

        
        # As you may have noticed, the above pos tags are a little confusing.
        
        # we use our own pos_tagger function to make things simpler to understand.
        wordnet_tagged = list(map(lambda x: (x[0], pos_tagger(x[1])), pos_tagged))
        
        lemmatized_sentence = []
        for word, tag in wordnet_tagged:
            if tag is None:
                # if there is no available tag, append the token as is
                lemmatized_sentence.append(word)
            else:       
                # else use the tag to lemmatize the token
                lemmatized_sentence.append(lemmatizer.lemmatize(word, tag))
        lemmatized_sentence = " ".join(lemmatized_sentence)
        lemmatized_data.append(lemmatized_sentence)
    return lemmatized_data

In [177]:
#CountVectorizer
def count_vectorizer(list):
    vectorizer = CountVectorizer(stop_words= 'english', lowercase=True, ngram_range=(1,3))
    matrix = vectorizer.fit_transform(list)
    count_table = pd.DataFrame(matrix.toarray(), columns=vectorizer.get_feature_names())
    return matrix, count_table

In [178]:
lemmatized_data = lemmatizing(list_of_donald_tweets)
X, count_table = count_vectorizer(lemmatized_data)
y = list_of_labels

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [179]:
#apply SVM machine learning algorithm
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)
from sklearn import svm 
svm = svm.SVC(kernel = 'linear', probability = True)
prob = svm.fit(X_train, y_train).predict_proba(X_test)
y_pred = svm.predict(X_test)

In [180]:
from sklearn.metrics import classification_report, confusion_matrix
y_pred_test = svm.predict(X_test)
CM = print(confusion_matrix(y_test, y_pred_test))

[[47  0  8]
 [ 2 18  9]
 [21  7 30]]


In [181]:
print(classification_report(y_test, y_pred_test))

              precision    recall  f1-score   support

           0       0.67      0.85      0.75        55
           1       0.72      0.62      0.67        29
           2       0.64      0.52      0.57        58

    accuracy                           0.67       142
   macro avg       0.68      0.66      0.66       142
weighted avg       0.67      0.67      0.66       142



# Hillary Clinton

In [182]:
target = 'Hillary Clinton'
df_target = df[df.Target == target]

df_target

Unnamed: 0                                              Tweet  \
0              0  @tedcruz And, #HandOverTheServer she wiped cle...   
1              1  Hillary is our best choice if we truly want to...   
2              2  @TheView I think our country is ready for a fe...   
3              3  I just gave an unhealthy amount of my hard-ear...   
4              4  @PortiaABoulger Thank you for adding me to you...   
...          ...                                                ...   
3878         964  .@HillaryClinton Looking 4ward 2 hearing your ...   
3879         965  @mataharikrishna I'm loving it too! Draw that ...   
3880         966  @finneyk Can't stand @msnbc anymore, but hope ...   
3881         967  Hillary can't create jobs! Last time she had a...   
3882         968  It's amazing to me how if you want a secure bo...   

               Target   Stance  \
0     Hillary Clinton  AGAINST   
1     Hillary Clinton    FAVOR   
2     Hillary Clinton  AGAINST   
3     Hillary Clinton  AGAINST   
4     Hillary Clinton     NONE   
...               ...      ...   
3878  Hillary Clinton    FAVOR   
3879  Hillary Clinton     NONE   
3880  Hillary Clinton    FAVOR   
3881  Hillary Clinton  AGAINST   
3882  Hillary Clinton     NONE   

                                        Opinion Towards Sentiment  
0     1.  The tweet explicitly expresses opinion abo...       neg  
1     1.  The tweet explicitly expresses opinion abo...       pos  
2     1.  The tweet explicitly expresses opinion abo...       neg  
3     1.  The tweet explicitly expresses opinion abo...       neg  
4     3.  The tweet is not explicitly expressing opi...       pos  
...                                                 ...       ...  
3878  1.  The tweet explicitly expresses opinion abo...       pos  
3879  2. The tweet does NOT expresses opinion about ...       pos  
3880  1.  The tweet explicitly expresses opinion abo...       pos  
3881  1.  The tweet explicitly expresses opinion abo...       neg  
3882  2. The tweet does NOT expresses opinion about ...       neg  

[984 rows x 6 columns]

In [183]:
df_target = df_target.drop('Unnamed: 0', axis='columns')
df_target = df_target.reset_index()
df_target = df_target.drop('index', axis='columns')

df_target

Tweet           Target  \
0    @tedcruz And, #HandOverTheServer she wiped cle...  Hillary Clinton   
1    Hillary is our best choice if we truly want to...  Hillary Clinton   
2    @TheView I think our country is ready for a fe...  Hillary Clinton   
3    I just gave an unhealthy amount of my hard-ear...  Hillary Clinton   
4    @PortiaABoulger Thank you for adding me to you...  Hillary Clinton   
..                                                 ...              ...   
979  .@HillaryClinton Looking 4ward 2 hearing your ...  Hillary Clinton   
980  @mataharikrishna I'm loving it too! Draw that ...  Hillary Clinton   
981  @finneyk Can't stand @msnbc anymore, but hope ...  Hillary Clinton   
982  Hillary can't create jobs! Last time she had a...  Hillary Clinton   
983  It's amazing to me how if you want a secure bo...  Hillary Clinton   

      Stance                                    Opinion Towards Sentiment  
0    AGAINST  1.  The tweet explicitly expresses opinion abo...       neg  
1      FAVOR  1.  The tweet explicitly expresses opinion abo...       pos  
2    AGAINST  1.  The tweet explicitly expresses opinion abo...       neg  
3    AGAINST  1.  The tweet explicitly expresses opinion abo...       neg  
4       NONE  3.  The tweet is not explicitly expressing opi...       pos  
..       ...                                                ...       ...  
979    FAVOR  1.  The tweet explicitly expresses opinion abo...       pos  
980     NONE  2. The tweet does NOT expresses opinion about ...       pos  
981    FAVOR  1.  The tweet explicitly expresses opinion abo...       pos  
982  AGAINST  1.  The tweet explicitly expresses opinion abo...       neg  
983     NONE  2. The tweet does NOT expresses opinion about ...       neg  

[984 rows x 5 columns]

In [184]:
list_of_hillary_tweets = []
for t in range(len(df_target)):
    list_of_hillary_tweets.append(df_target['Tweet'][t])
list_of_hillary_tweets

['@tedcruz And, #HandOverTheServer she wiped clean + 30k deleted emails, explains dereliction of duty/lies re #Benghazi,etc #tcot',
 'Hillary is our best choice if we truly want to continue being a progressive nation. #Ohio',
 "@TheView I think our country is ready for a female pres, it can't ever be Hillary",
 "I just gave an unhealthy amount of my hard-earned money away to the big gov't & untrustworthy IRS. #WhyImNotVotingForHillary",
 '@PortiaABoulger Thank you for adding me to your list',
 "Hillary can not win. Here's hoping the Dems offer a real candidate like Warren. #Warren2016",
 'Respect FOR the law and respect BY the law Yes, needed desperately.  #BaltimoreRiots',
 "I don't want to be appointed to an Ambassador post.",
 '#StopHillary2016 @HillaryClinton if there was a woman with integrity and honesty I would vote for such as woman president, NO',
 '@HillaryClinton End lawless #ClintonFoundation. Jail Butcher of #Benghazi. #Arrest rapist #BillClinton. #HillaryClinton',
 'Use y

In [185]:
# labels for hillary clinton df
list_of_labels = []
for t in range(len(df_target)):
    if df_target['Stance'][t] == 'FAVOR':
        list_of_labels.append(1)
    elif df_target['Stance'][t] == 'AGAINST':
        list_of_labels.append(2)
    else:
        list_of_labels.append(0) 

In [186]:
print(len(df_target), len(list_of_labels))

984 984


In [187]:
list_of_labels

[2,
 1,
 2,
 2,
 0,
 2,
 0,
 0,
 2,
 2,
 2,
 2,
 1,
 0,
 2,
 0,
 1,
 2,
 0,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 0,
 2,
 2,
 0,
 2,
 1,
 2,
 2,
 0,
 2,
 2,
 0,
 2,
 2,
 2,
 2,
 0,
 2,
 1,
 0,
 1,
 2,
 1,
 2,
 0,
 1,
 0,
 2,
 1,
 2,
 0,
 1,
 0,
 0,
 2,
 0,
 2,
 0,
 2,
 1,
 1,
 1,
 0,
 0,
 1,
 2,
 0,
 2,
 2,
 1,
 2,
 0,
 1,
 2,
 1,
 2,
 1,
 0,
 1,
 1,
 1,
 2,
 0,
 1,
 1,
 1,
 2,
 0,
 2,
 2,
 1,
 2,
 2,
 2,
 0,
 2,
 2,
 0,
 1,
 2,
 0,
 2,
 0,
 0,
 2,
 2,
 0,
 2,
 2,
 2,
 0,
 0,
 2,
 0,
 0,
 1,
 0,
 1,
 2,
 2,
 0,
 1,
 1,
 2,
 2,
 2,
 1,
 0,
 0,
 2,
 2,
 0,
 0,
 0,
 2,
 2,
 2,
 2,
 2,
 0,
 2,
 2,
 2,
 2,
 2,
 2,
 0,
 2,
 0,
 0,
 2,
 2,
 2,
 0,
 1,
 0,
 1,
 1,
 2,
 1,
 1,
 0,
 1,
 2,
 2,
 1,
 2,
 2,
 1,
 1,
 2,
 0,
 2,
 2,
 2,
 2,
 2,
 2,
 0,
 2,
 2,
 1,
 2,
 0,
 0,
 1,
 2,
 2,
 1,
 0,
 2,
 1,
 2,
 0,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 2,
 0,
 2,
 1,
 1,
 2,
 0,
 2,
 1,
 2,
 0,
 2,
 2,
 2,
 1,
 0,
 1,
 0,
 2,
 2,
 0,
 2,
 2,
 1,
 0,
 0,
 2,
 1,
 2,
 0,
 2,
 0,
 0,
 2,
 0,
 0,
 2,
 1,
 2,


In [188]:
pip install nltk

Defaulting to user installation because normal site-packages is not writeable
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))) - skipping
Note: you may need to restart the kernel to use updated packages.


In [189]:
import nltk

In [190]:
nltk.download('averaged_perceptron_tagger')

[nltk_data] Error loading averaged_perceptron_tagger: HTTP Error 401:
[nltk_data]     Unauthorized


False

In [191]:
# WORDNET LEMMATIZER (with appropriate pos tags)

from nltk.stem import WordNetLemmatizer
#nltk.download('averaged_perceptron_tagger')
from nltk.corpus import wordnet
from nltk.corpus import stopwords

nltk.download('stopwords')

[nltk_data] Error loading stopwords: HTTP Error 401: Unauthorized


False

In [192]:
 
lemmatizer = WordNetLemmatizer()
 
# Define function to lemmatize each word with its POS tag
 
# POS_TAGGER_FUNCTION : TYPE 1
def pos_tagger(nltk_tag):
    if nltk_tag.startswith('J'):
        return wordnet.ADJ
    elif nltk_tag.startswith('V'):
        return wordnet.VERB
    elif nltk_tag.startswith('N'):
        return wordnet.NOUN
    elif nltk_tag.startswith('R'):
        return wordnet.ADV
    else:         
        return None
 
def lemmatizing(data):
    lemmatized_data = []
    for i in range(len(data)):
        sentence = data[i]

        # tokenize the sentence and find the POS tag for each token
        word_tokens = nltk.wordpunct_tokenize(sentence)
 
        pos_tagged = nltk.pos_tag(word_tokens) 

        
        # As you may have noticed, the above pos tags are a little confusing.
        
        # we use our own pos_tagger function to make things simpler to understand.
        wordnet_tagged = list(map(lambda x: (x[0], pos_tagger(x[1])), pos_tagged))
        
        lemmatized_sentence = []
        for word, tag in wordnet_tagged:
            if tag is None:
                # if there is no available tag, append the token as is
                lemmatized_sentence.append(word)
            else:       
                # else use the tag to lemmatize the token
                lemmatized_sentence.append(lemmatizer.lemmatize(word, tag))
        lemmatized_sentence = " ".join(lemmatized_sentence)
        lemmatized_data.append(lemmatized_sentence)
    return lemmatized_data

In [193]:
#CountVectorizer
def count_vectorizer(list):
    vectorizer = CountVectorizer(stop_words= 'english', lowercase=True, ngram_range=(1,3))
    matrix = vectorizer.fit_transform(list)
    count_table = pd.DataFrame(matrix.toarray(), columns=vectorizer.get_feature_names())
    return matrix, count_table

In [194]:
os.environ['NLTK_DATA']

'C:/Users/13630/Desktop/NLTK_datasets/corpora'

In [195]:
import os
os.environ['NLTK_DATA'] = str('C:/Users/13630/Desktop/NLTK_datasets/corpora')
lemmatized_data = lemmatizing(list_of_hillary_tweets)
X, count_table = count_vectorizer(lemmatized_data)
y = list_of_labels

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


refer to this website https://investigate.ai/text-analysis/counting-words-with-scikit-learns-countvectorizer/

In [196]:
#apply SVM machine learning algorithm
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)
from sklearn import svm 
svm = svm.SVC(kernel = 'linear', probability = True)
prob = svm.fit(X_train, y_train).predict_proba(X_test)
y_pred = svm.predict(X_test)

In [197]:
from sklearn.metrics import classification_report, confusion_matrix
y_pred_test = svm.predict(X_test)
CM = print(confusion_matrix(y_test, y_pred_test))

[[32  1 19]
 [ 4  9 16]
 [13  5 98]]


In [198]:
print(classification_report(y_test, y_pred_test))

              precision    recall  f1-score   support

           0       0.65      0.62      0.63        52
           1       0.60      0.31      0.41        29
           2       0.74      0.84      0.79       116

    accuracy                           0.71       197
   macro avg       0.66      0.59      0.61       197
weighted avg       0.69      0.71      0.69       197



# Feminist Movement 

In [199]:
target = 'Feminist Movement'
df_target = df[df.Target == target]

df_target

Unnamed: 0                                              Tweet  \
1008        1008  Always a delight to see chest-drumming alpha m...   
1009        1009  Sometimes I overheat and want to take off my s...   
1010        1010  If feminists spent 1/2 as much time reading pa...   
1011        1011  Stupid Feminists, the civilization you take fo...   
1012        1012  YOU'RE A GIRL AND HAVE A SEX DRIVE!? YOU MUST ...   
...          ...                                                ...   
3583         669  @Maisie_Williams is our hero with her #LikeAGi...   
3584         670  Rather be an "ugly" feminist then be these sad...   
3585         671  iamNovaah: RT ChrzOC: Bitches be running wild....   
3586         672  @angerelle you disagree that people should str...   
3587         673  #Rapeculture is basically a FABLE. It has almo...   

                 Target   Stance  \
1008  Feminist Movement    FAVOR   
1009  Feminist Movement    FAVOR   
1010  Feminist Movement  AGAINST   
1011  Feminist Movement  AGAINST   
1012  Feminist Movement    FAVOR   
...                 ...      ...   
3583  Feminist Movement    FAVOR   
3584  Feminist Movement    FAVOR   
3585  Feminist Movement  AGAINST   
3586  Feminist Movement    FAVOR   
3587  Feminist Movement  AGAINST   

                                        Opinion Towards Sentiment  
1008  1.  The tweet explicitly expresses opinion abo...       neg  
1009  1.  The tweet explicitly expresses opinion abo...       neg  
1010  1.  The tweet explicitly expresses opinion abo...       neg  
1011  1.  The tweet explicitly expresses opinion abo...       neg  
1012  1.  The tweet explicitly expresses opinion abo...       neg  
...                                                 ...       ...  
3583  1.  The tweet explicitly expresses opinion abo...       pos  
3584  1.  The tweet explicitly expresses opinion abo...       neg  
3585  1.  The tweet explicitly expresses opinion abo...       neg  
3586  2. The tweet does NOT expresses opinion about ...       neg  
3587  1.  The tweet explicitly expresses opinion abo...       neg  

[949 rows x 6 columns]

In [200]:
df_target = df_target.drop('Unnamed: 0', axis='columns')
df_target = df_target.reset_index()
df_target = df_target.drop('index', axis='columns')

df_target

Tweet             Target  \
0    Always a delight to see chest-drumming alpha m...  Feminist Movement   
1    Sometimes I overheat and want to take off my s...  Feminist Movement   
2    If feminists spent 1/2 as much time reading pa...  Feminist Movement   
3    Stupid Feminists, the civilization you take fo...  Feminist Movement   
4    YOU'RE A GIRL AND HAVE A SEX DRIVE!? YOU MUST ...  Feminist Movement   
..                                                 ...                ...   
944  @Maisie_Williams is our hero with her #LikeAGi...  Feminist Movement   
945  Rather be an "ugly" feminist then be these sad...  Feminist Movement   
946  iamNovaah: RT ChrzOC: Bitches be running wild....  Feminist Movement   
947  @angerelle you disagree that people should str...  Feminist Movement   
948  #Rapeculture is basically a FABLE. It has almo...  Feminist Movement   

      Stance                                    Opinion Towards Sentiment  
0      FAVOR  1.  The tweet explicitly expresses opinion abo...       neg  
1      FAVOR  1.  The tweet explicitly expresses opinion abo...       neg  
2    AGAINST  1.  The tweet explicitly expresses opinion abo...       neg  
3    AGAINST  1.  The tweet explicitly expresses opinion abo...       neg  
4      FAVOR  1.  The tweet explicitly expresses opinion abo...       neg  
..       ...                                                ...       ...  
944    FAVOR  1.  The tweet explicitly expresses opinion abo...       pos  
945    FAVOR  1.  The tweet explicitly expresses opinion abo...       neg  
946  AGAINST  1.  The tweet explicitly expresses opinion abo...       neg  
947    FAVOR  2. The tweet does NOT expresses opinion about ...       neg  
948  AGAINST  1.  The tweet explicitly expresses opinion abo...       neg  

[949 rows x 5 columns]

In [201]:
list_of_feminist_tweets = []
for t in range(len(df_target)):
    list_of_feminist_tweets.append(df_target['Tweet'][t])
list_of_feminist_tweets

['Always a delight to see chest-drumming alpha males hiss and scuttle backwards up the wall when a feminist enters the room. #manly #SemST',
 "Sometimes I overheat and want to take off my shirt but can't because of social expectations of people with breasts. ;n; #SemST",
 'If feminists spent 1/2 as much time reading papers as they do tumblr they would be real people, not ignorant sexist bigots. #SemST',
 'Stupid Feminists, the civilization you take for granted was built with the labour, blood sweat and tears of men. #SemST',
 "YOU'RE A GIRL AND HAVE A SEX DRIVE!? YOU MUST BE A SLUT! #feminist #SemST",
 "Suns out....  Dresses out...  #StreetHarassment out...  This shouldn't be daily life  #YesAllWomen @EverydaySexism #SemST",
 "Women's rights are #humanrights! Join the #CPDvoices twitter rally at 3pm ET if you agree! #CPD48 #SemST",
 "So you support unequal pricing based on gender @CamilleBogrand?  Don't you normally call that sexism?  #EqualPayDay #SemST",
 'These pics of #pornstars wi

In [202]:
list_of_labels = []
for t in range(len(df_target)):
    if df_target['Stance'][t] == 'FAVOR':
        list_of_labels.append(1)
    elif df_target['Stance'][t] == 'AGAINST':
        list_of_labels.append(2)
    else:
        list_of_labels.append(0) 

In [203]:
print(len(list_of_labels))

949


In [204]:
pip install nltk

Defaulting to user installation because normal site-packages is not writeable
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))) - skipping
Note: you may need to restart the kernel to use updated packages.


In [205]:
import nltk

In [206]:
nltk.download('averaged_perceptron_tagger')

[nltk_data] Error loading averaged_perceptron_tagger: HTTP Error 401:
[nltk_data]     Unauthorized


False

In [207]:
# WORDNET LEMMATIZER (with appropriate pos tags)

from nltk.stem import WordNetLemmatizer
#nltk.download('averaged_perceptron_tagger')
from nltk.corpus import wordnet
from nltk.corpus import stopwords

nltk.download('stopwords')

[nltk_data] Error loading stopwords: HTTP Error 401: Unauthorized


False

In [208]:
 
lemmatizer = WordNetLemmatizer()
 
# Define function to lemmatize each word with its POS tag
 
# POS_TAGGER_FUNCTION : TYPE 1
def pos_tagger(nltk_tag):
    if nltk_tag.startswith('J'):
        return wordnet.ADJ
    elif nltk_tag.startswith('V'):
        return wordnet.VERB
    elif nltk_tag.startswith('N'):
        return wordnet.NOUN
    elif nltk_tag.startswith('R'):
        return wordnet.ADV
    else:         
        return None
 
def lemmatizing(data):
    lemmatized_data = []
    for i in range(len(data)):
        sentence = data[i]

        # tokenize the sentence and find the POS tag for each token
        word_tokens = nltk.wordpunct_tokenize(sentence)
 
        pos_tagged = nltk.pos_tag(word_tokens) 

        
        # As you may have noticed, the above pos tags are a little confusing.
        
        # we use our own pos_tagger function to make things simpler to understand.
        wordnet_tagged = list(map(lambda x: (x[0], pos_tagger(x[1])), pos_tagged))
        
        lemmatized_sentence = []
        for word, tag in wordnet_tagged:
            if tag is None:
                # if there is no available tag, append the token as is
                lemmatized_sentence.append(word)
            else:       
                # else use the tag to lemmatize the token
                lemmatized_sentence.append(lemmatizer.lemmatize(word, tag))
        lemmatized_sentence = " ".join(lemmatized_sentence)
        lemmatized_data.append(lemmatized_sentence)
    return lemmatized_data

In [209]:
#CountVectorizer
def count_vectorizer(list):
    vectorizer = CountVectorizer(stop_words= 'english', lowercase=True, ngram_range=(1,3))
    matrix = vectorizer.fit_transform(list)
    count_table = pd.DataFrame(matrix.toarray(), columns=vectorizer.get_feature_names())
    return matrix, count_table

In [210]:
os.environ['NLTK_DATA']

'C:/Users/13630/Desktop/NLTK_datasets/corpora'

In [211]:
import os
os.environ['NLTK_DATA'] = str('C:/Users/13630/Desktop/NLTK_datasets/corpora')
lemmatized_data = lemmatizing(list_of_feminist_tweets)
X, count_table = count_vectorizer(lemmatized_data)
y = list_of_labels

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


refer to this website https://investigate.ai/text-analysis/counting-words-with-scikit-learns-countvectorizer/

In [212]:
#apply SVM machine learning algorithm
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)
from sklearn import svm 
svm = svm.SVC(kernel = 'linear', probability = True)
prob = svm.fit(X_train, y_train).predict_proba(X_test)
y_pred = svm.predict(X_test)

In [213]:
from sklearn.metrics import classification_report, confusion_matrix
y_pred_test = svm.predict(X_test)
CM = print(confusion_matrix(y_test, y_pred_test))

[[ 3  0 28]
 [ 3 15 31]
 [ 3 12 95]]


In [214]:
print(classification_report(y_test, y_pred_test))

              precision    recall  f1-score   support

           0       0.33      0.10      0.15        31
           1       0.56      0.31      0.39        49
           2       0.62      0.86      0.72       110

    accuracy                           0.59       190
   macro avg       0.50      0.42      0.42       190
weighted avg       0.55      0.59      0.54       190



# Legalization of Abortion 

In [215]:
target = 'Legalization of Abortion'
df_target = df[df.Target == target]

df_target

Unnamed: 0                                              Tweet  \
50            50  Just laid down the law on abortion in my bioet...   
51            51  @tooprettyclub Are you OK with #GOP males tell...   
52            52  If you don't want your kid, put it up for adop...   
53            53  @RedAlert -there should be a "stigma" to butch...   
54            54  But isn't that the problem then. Not enough fa...   
...          ...                                                ...   
4158        1244  @MetalheadMonty @tom_six I followed him before...   
4159        1245  For he who avenges blood remembers, he does no...   
4160        1246  Life is sacred on all levels. Abortion does no...   
4161        1247  @ravensymone U refer to "WE" which ="YOU" & a ...   
4162        1248  Al Robertson's mom #DuckDynasty  chose life as...   

                        Target   Stance  \
50    Legalization of Abortion  AGAINST   
51    Legalization of Abortion    FAVOR   
52    Legalization of Abortion  AGAINST   
53    Legalization of Abortion  AGAINST   
54    Legalization of Abortion     NONE   
...                        ...      ...   
4158  Legalization of Abortion     NONE   
4159  Legalization of Abortion  AGAINST   
4160  Legalization of Abortion  AGAINST   
4161  Legalization of Abortion  AGAINST   
4162  Legalization of Abortion  AGAINST   

                                        Opinion Towards Sentiment  
50    1.  The tweet explicitly expresses opinion abo...       neg  
51    1.  The tweet explicitly expresses opinion abo...       neg  
52    1.  The tweet explicitly expresses opinion abo...       neg  
53    1.  The tweet explicitly expresses opinion abo...       neg  
54    2. The tweet does NOT expresses opinion about ...       neg  
...                                                 ...       ...  
4158  2. The tweet does NOT expresses opinion about ...       neg  
4159  1.  The tweet explicitly expresses opinion abo...     other  
4160  1.  The tweet explicitly expresses opinion abo...     other  
4161  1.  The tweet explicitly expresses opinion abo...       neg  
4162  1.  The tweet explicitly expresses opinion abo...     other  

[933 rows x 6 columns]

In [216]:
df_target = df_target.drop('Unnamed: 0', axis='columns')
df_target = df_target.reset_index()
df_target = df_target.drop('index', axis='columns')

df_target

Tweet  \
0    Just laid down the law on abortion in my bioet...   
1    @tooprettyclub Are you OK with #GOP males tell...   
2    If you don't want your kid, put it up for adop...   
3    @RedAlert -there should be a "stigma" to butch...   
4    But isn't that the problem then. Not enough fa...   
..                                                 ...   
928  @MetalheadMonty @tom_six I followed him before...   
929  For he who avenges blood remembers, he does no...   
930  Life is sacred on all levels. Abortion does no...   
931  @ravensymone U refer to "WE" which ="YOU" & a ...   
932  Al Robertson's mom #DuckDynasty  chose life as...   

                       Target   Stance  \
0    Legalization of Abortion  AGAINST   
1    Legalization of Abortion    FAVOR   
2    Legalization of Abortion  AGAINST   
3    Legalization of Abortion  AGAINST   
4    Legalization of Abortion     NONE   
..                        ...      ...   
928  Legalization of Abortion     NONE   
929  Legalization of Abortion  AGAINST   
930  Legalization of Abortion  AGAINST   
931  Legalization of Abortion  AGAINST   
932  Legalization of Abortion  AGAINST   

                                       Opinion Towards Sentiment  
0    1.  The tweet explicitly expresses opinion abo...       neg  
1    1.  The tweet explicitly expresses opinion abo...       neg  
2    1.  The tweet explicitly expresses opinion abo...       neg  
3    1.  The tweet explicitly expresses opinion abo...       neg  
4    2. The tweet does NOT expresses opinion about ...       neg  
..                                                 ...       ...  
928  2. The tweet does NOT expresses opinion about ...       neg  
929  1.  The tweet explicitly expresses opinion abo...     other  
930  1.  The tweet explicitly expresses opinion abo...     other  
931  1.  The tweet explicitly expresses opinion abo...       neg  
932  1.  The tweet explicitly expresses opinion abo...     other  

[933 rows x 5 columns]

In [217]:
list_of_abortion_tweets = []
for t in range(len(df_target)):
    list_of_abortion_tweets.append(df_target['Tweet'][t])
list_of_abortion_tweets

['Just laid down the law on abortion in my bioethics class. #Catholic',
 "@tooprettyclub Are you OK with #GOP males telling you what you can and can't do with your own body?",
 "If you don't want your kid, put it up for adoption. #sorrynotsorry",
 '@RedAlert -there should be a "stigma" to butchering pre-born children - its a horrendous crime against humanity.  #murder',
 "But isn't that the problem then. Not enough faith. #gaystapo #socialism",
 'Life is our first and most basic human right.',
 "Rise & Shine its a new day & you're alive. Thank God 4 another day of precious life. #Christian #Catholic #TeamJesus",
 "Lmao my school thinks giving women the right to an abortion is against feminism. They don't know feminism #wtf",
 '@AsaSoltan putting abortion in with choices for women just won my heart over. Yaaaaaas! #shahs',
 'Last meeting of the year tonight! 7:00 pm in Case Hall room 334A. Come one come all! Pizza and pop will be provided!',
 "FACT: 17% of today's population is equivale

In [218]:
list_of_labels = []
for t in range(len(df_target)):
    if df_target['Stance'][t] == 'FAVOR':
        list_of_labels.append(1)
    elif df_target['Stance'][t] == 'AGAINST':
        list_of_labels.append(2)
    else:
        list_of_labels.append(0) 

In [219]:
list_of_labels

[2,
 1,
 2,
 2,
 0,
 2,
 2,
 1,
 1,
 0,
 0,
 0,
 0,
 2,
 2,
 2,
 1,
 2,
 2,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 2,
 0,
 0,
 1,
 1,
 2,
 2,
 2,
 2,
 1,
 1,
 0,
 2,
 2,
 1,
 1,
 1,
 2,
 2,
 0,
 0,
 2,
 0,
 2,
 2,
 2,
 2,
 2,
 0,
 0,
 2,
 2,
 0,
 1,
 2,
 1,
 2,
 1,
 1,
 2,
 2,
 2,
 2,
 0,
 2,
 0,
 1,
 2,
 1,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 2,
 0,
 0,
 2,
 2,
 0,
 1,
 0,
 2,
 2,
 0,
 2,
 1,
 1,
 2,
 2,
 0,
 2,
 2,
 2,
 2,
 0,
 2,
 0,
 0,
 2,
 0,
 2,
 2,
 2,
 0,
 0,
 0,
 0,
 2,
 2,
 0,
 1,
 2,
 2,
 0,
 0,
 2,
 2,
 1,
 0,
 0,
 2,
 0,
 1,
 2,
 0,
 0,
 0,
 1,
 0,
 0,
 2,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 2,
 0,
 2,
 2,
 0,
 0,
 2,
 1,
 0,
 2,
 1,
 0,
 1,
 1,
 0,
 2,
 0,
 0,
 2,
 0,
 1,
 0,
 2,
 2,
 0,
 0,
 0,
 2,
 2,
 1,
 1,
 2,
 0,
 2,
 0,
 2,
 2,
 0,
 0,
 1,
 2,
 2,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 2,
 1,
 2,
 1,
 2,
 0,
 0,
 2,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 0,
 2,
 2,
 0,
 2,
 0,
 0,
 2,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 1,
 0,
 2,
 1,
 0,


In [220]:
pip install nltk

Defaulting to user installation because normal site-packages is not writeable
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))) - skipping
Note: you may need to restart the kernel to use updated packages.


In [221]:
import nltk

In [222]:
nltk.download('averaged_perceptron_tagger')

[nltk_data] Error loading averaged_perceptron_tagger: HTTP Error 401:
[nltk_data]     Unauthorized


False

In [223]:
# WORDNET LEMMATIZER (with appropriate pos tags)

from nltk.stem import WordNetLemmatizer
#nltk.download('averaged_perceptron_tagger')
from nltk.corpus import wordnet
from nltk.corpus import stopwords

nltk.download('stopwords')

[nltk_data] Error loading stopwords: HTTP Error 401: Unauthorized


False

In [224]:
 
lemmatizer = WordNetLemmatizer()
 
# Define function to lemmatize each word with its POS tag
 
# POS_TAGGER_FUNCTION : TYPE 1
def pos_tagger(nltk_tag):
    if nltk_tag.startswith('J'):
        return wordnet.ADJ
    elif nltk_tag.startswith('V'):
        return wordnet.VERB
    elif nltk_tag.startswith('N'):
        return wordnet.NOUN
    elif nltk_tag.startswith('R'):
        return wordnet.ADV
    else:         
        return None
 
def lemmatizing(data):
    lemmatized_data = []
    for i in range(len(data)):
        sentence = data[i]

        # tokenize the sentence and find the POS tag for each token
        word_tokens = nltk.wordpunct_tokenize(sentence)
 
        pos_tagged = nltk.pos_tag(word_tokens) 

        
        # As you may have noticed, the above pos tags are a little confusing.
        
        # we use our own pos_tagger function to make things simpler to understand.
        wordnet_tagged = list(map(lambda x: (x[0], pos_tagger(x[1])), pos_tagged))
        
        lemmatized_sentence = []
        for word, tag in wordnet_tagged:
            if tag is None:
                # if there is no available tag, append the token as is
                lemmatized_sentence.append(word)
            else:       
                # else use the tag to lemmatize the token
                lemmatized_sentence.append(lemmatizer.lemmatize(word, tag))
        lemmatized_sentence = " ".join(lemmatized_sentence)
        lemmatized_data.append(lemmatized_sentence)
    return lemmatized_data

In [225]:
#CountVectorizer
def count_vectorizer(list):
    vectorizer = CountVectorizer(stop_words= 'english', lowercase=True, ngram_range=(1,3))
    matrix = vectorizer.fit_transform(list)
    count_table = pd.DataFrame(matrix.toarray(), columns=vectorizer.get_feature_names())
    return matrix, count_table

In [226]:
os.environ['NLTK_DATA']

'C:/Users/13630/Desktop/NLTK_datasets/corpora'

In [227]:
import os
os.environ['NLTK_DATA'] = str('C:/Users/13630/Desktop/NLTK_datasets/corpora')
lemmatized_data = lemmatizing(list_of_abortion_tweets)
X, count_table = count_vectorizer(lemmatized_data)
y = list_of_labels

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


refer to this website https://investigate.ai/text-analysis/counting-words-with-scikit-learns-countvectorizer/

In [228]:
#apply SVM machine learning algorithm
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)
from sklearn import svm 
svm = svm.SVC(kernel = 'linear', probability = True)
prob = svm.fit(X_train, y_train).predict_proba(X_test)
y_pred = svm.predict(X_test)

In [229]:
from sklearn.metrics import classification_report, confusion_matrix
y_pred_test = svm.predict(X_test)
CM = print(confusion_matrix(y_test, y_pred_test))

[[22  0 19]
 [ 3  8 24]
 [11  4 96]]


In [230]:
print(classification_report(y_test, y_pred_test))

              precision    recall  f1-score   support

           0       0.61      0.54      0.57        41
           1       0.67      0.23      0.34        35
           2       0.69      0.86      0.77       111

    accuracy                           0.67       187
   macro avg       0.66      0.54      0.56       187
weighted avg       0.67      0.67      0.64       187



# Atheism

In [231]:
target = 'Atheism'
df_target = df[df.Target == target]

df_target

Unnamed: 0                                              Tweet   Target  \
100          100  dear lord thank u for all of ur blessings forg...  Atheism   
101          101  Blessed are the peacemakers, for they shall be...  Atheism   
102          102  I am not conformed to this world. I am transfo...  Atheism   
103          103  Salah should be prayed with #focus and #unders...  Atheism   
104          104  And stay in your houses and do not display you...  Atheism   
...          ...                                                ...      ...   
3129         215  1of 2 #Never be #afraid to and never #apologis...  Atheism   
3130         216  How soon do you think WWIII &WWWIV will begin?...  Atheism   
3131         217  The humble trust in God: 'Whoever leans on, tr...  Atheism   
3132         218  Where will you be when @NewHorizons2015 flies ...  Atheism   
3133         219  No one can out woo God in the woo department -...  Atheism   

       Stance                                    Opinion Towards Sentiment  
100   AGAINST  2. The tweet does NOT expresses opinion about ...       pos  
101   AGAINST  2. The tweet does NOT expresses opinion about ...       pos  
102   AGAINST  2. The tweet does NOT expresses opinion about ...       pos  
103   AGAINST  2. The tweet does NOT expresses opinion about ...       pos  
104   AGAINST  2. The tweet does NOT expresses opinion about ...       neg  
...       ...                                                ...       ...  
3129  AGAINST  1.  The tweet explicitly expresses opinion abo...       pos  
3130    FAVOR  1.  The tweet explicitly expresses opinion abo...       neg  
3131  AGAINST  1.  The tweet explicitly expresses opinion abo...       pos  
3132    FAVOR  1.  The tweet explicitly expresses opinion abo...       pos  
3133  AGAINST  1.  The tweet explicitly expresses opinion abo...       pos  

[733 rows x 6 columns]

In [232]:
df_target = df_target.drop('Unnamed: 0', axis='columns')
df_target = df_target.reset_index()
df_target = df_target.drop('index', axis='columns')

df_target

Tweet   Target   Stance  \
0    dear lord thank u for all of ur blessings forg...  Atheism  AGAINST   
1    Blessed are the peacemakers, for they shall be...  Atheism  AGAINST   
2    I am not conformed to this world. I am transfo...  Atheism  AGAINST   
3    Salah should be prayed with #focus and #unders...  Atheism  AGAINST   
4    And stay in your houses and do not display you...  Atheism  AGAINST   
..                                                 ...      ...      ...   
728  1of 2 #Never be #afraid to and never #apologis...  Atheism  AGAINST   
729  How soon do you think WWIII &WWWIV will begin?...  Atheism    FAVOR   
730  The humble trust in God: 'Whoever leans on, tr...  Atheism  AGAINST   
731  Where will you be when @NewHorizons2015 flies ...  Atheism    FAVOR   
732  No one can out woo God in the woo department -...  Atheism  AGAINST   

                                       Opinion Towards Sentiment  
0    2. The tweet does NOT expresses opinion about ...       pos  
1    2. The tweet does NOT expresses opinion about ...       pos  
2    2. The tweet does NOT expresses opinion about ...       pos  
3    2. The tweet does NOT expresses opinion about ...       pos  
4    2. The tweet does NOT expresses opinion about ...       neg  
..                                                 ...       ...  
728  1.  The tweet explicitly expresses opinion abo...       pos  
729  1.  The tweet explicitly expresses opinion abo...       neg  
730  1.  The tweet explicitly expresses opinion abo...       pos  
731  1.  The tweet explicitly expresses opinion abo...       pos  
732  1.  The tweet explicitly expresses opinion abo...       pos  

[733 rows x 5 columns]

In [233]:
list_of_atheism_tweets = []
for t in range(len(df_target)):
    list_of_atheism_tweets.append(df_target['Tweet'][t])
list_of_atheism_tweets

['dear lord thank u for all of ur blessings forgive my sins lord give me strength and energy for this busy day ahead #blessed #hope #SemST',
 'Blessed are the peacemakers, for they shall be called children of God. Matthew 5:9 #scripture #peace #SemST',
 'I am not conformed to this world. I am transformed by the renewing of my mind. #ISpeakLife #God #2014 #SemST',
 'Salah should be prayed with #focus and #understanding. #Allah warns against #lazy prayers done just for #show Surah Al-Maoon 107:4-6 #SemST',
 'And stay in your houses and do not display yourselves like that of the times of ignorance." [Quran 33:33].#islam #SemST',
 'If we are unsure whether something is halal or haram, we should leave it - this will #safeguard our #deen #rule #SemST',
 'Papa God, i pray that You shower me with more patience.  #worththewait #SemST',
 "Now that the SCOC has ruled Canadians have freedom from religion, can someone tell Harper to dummy his 'god bless Canada'. #cdnpoli #SemST",
 'Wow, unsubstanti

In [234]:
list_of_labels = []
for t in range(len(df_target)):
    if df_target['Stance'][t] == 'FAVOR':
        list_of_labels.append(1)
    elif df_target['Stance'][t] == 'AGAINST':
        list_of_labels.append(2)
    else:
        list_of_labels.append(0) 

In [235]:
list_of_labels

[2,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 0,
 0,
 1,
 2,
 2,
 2,
 2,
 2,
 0,
 2,
 1,
 2,
 2,
 1,
 0,
 2,
 2,
 1,
 2,
 2,
 2,
 0,
 2,
 2,
 2,
 1,
 0,
 2,
 0,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 0,
 2,
 1,
 1,
 2,
 1,
 2,
 2,
 0,
 1,
 1,
 0,
 1,
 2,
 0,
 1,
 0,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 2,
 2,
 2,
 1,
 2,
 0,
 1,
 1,
 0,
 2,
 2,
 1,
 0,
 2,
 0,
 0,
 2,
 2,
 2,
 0,
 2,
 2,
 2,
 2,
 2,
 1,
 2,
 2,
 1,
 2,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 1,
 1,
 2,
 0,
 0,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 2,
 2,
 2,
 2,
 0,
 1,
 2,
 0,
 2,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 0,
 2,
 2,
 2,
 2,
 1,
 2,
 1,
 1,
 1,
 2,
 0,
 2,
 2,
 0,
 2,
 0,
 1,
 2,
 2,
 0,
 2,
 1,
 0,
 2,
 2,
 2,
 2,
 2,
 0,
 2,
 2,
 2,
 2,
 2,
 2,
 0,
 0,
 2,
 2,
 1,
 0,
 0,
 2,
 0,
 0,
 2,
 2,
 0,
 0,
 1,
 2,
 2,
 2,
 0,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 2,
 1,
 0,
 2,
 0,
 0,
 0,
 2,
 0,
 1,
 2,
 0,
 2,
 2,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 2,
 1,
 1,
 2,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 2,
 0,
 0,
 2,
 0,
 0,
 1,
 1,


In [236]:
pip install nltk

Defaulting to user installation because normal site-packages is not writeable
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))) - skipping
Note: you may need to restart the kernel to use updated packages.


In [237]:
import nltk

In [238]:
nltk.download('averaged_perceptron_tagger')

[nltk_data] Error loading averaged_perceptron_tagger: HTTP Error 401:
[nltk_data]     Unauthorized


False

In [239]:
# WORDNET LEMMATIZER (with appropriate pos tags)

from nltk.stem import WordNetLemmatizer
#nltk.download('averaged_perceptron_tagger')
from nltk.corpus import wordnet
from nltk.corpus import stopwords

nltk.download('stopwords')

[nltk_data] Error loading stopwords: HTTP Error 401: Unauthorized


False

In [240]:
 
lemmatizer = WordNetLemmatizer()
 
# Define function to lemmatize each word with its POS tag
 
# POS_TAGGER_FUNCTION : TYPE 1
def pos_tagger(nltk_tag):
    if nltk_tag.startswith('J'):
        return wordnet.ADJ
    elif nltk_tag.startswith('V'):
        return wordnet.VERB
    elif nltk_tag.startswith('N'):
        return wordnet.NOUN
    elif nltk_tag.startswith('R'):
        return wordnet.ADV
    else:         
        return None
 
def lemmatizing(data):
    lemmatized_data = []
    for i in range(len(data)):
        sentence = data[i]

        # tokenize the sentence and find the POS tag for each token
        word_tokens = nltk.wordpunct_tokenize(sentence)
 
        pos_tagged = nltk.pos_tag(word_tokens) 

        
        # As you may have noticed, the above pos tags are a little confusing.
        
        # we use our own pos_tagger function to make things simpler to understand.
        wordnet_tagged = list(map(lambda x: (x[0], pos_tagger(x[1])), pos_tagged))
        
        lemmatized_sentence = []
        for word, tag in wordnet_tagged:
            if tag is None:
                # if there is no available tag, append the token as is
                lemmatized_sentence.append(word)
            else:       
                # else use the tag to lemmatize the token
                lemmatized_sentence.append(lemmatizer.lemmatize(word, tag))
        lemmatized_sentence = " ".join(lemmatized_sentence)
        lemmatized_data.append(lemmatized_sentence)
    return lemmatized_data

In [241]:
#CountVectorizer
def count_vectorizer(list):
    vectorizer = CountVectorizer(stop_words= 'english', lowercase=True, ngram_range=(1,3))
    matrix = vectorizer.fit_transform(list)
    count_table = pd.DataFrame(matrix.toarray(), columns=vectorizer.get_feature_names())
    return matrix, count_table

In [242]:
os.environ['NLTK_DATA']

'C:/Users/13630/Desktop/NLTK_datasets/corpora'

In [243]:
import os
os.environ['NLTK_DATA'] = str('C:/Users/13630/Desktop/NLTK_datasets/corpora')
lemmatized_data = lemmatizing(list_of_atheism_tweets)
X, count_table = count_vectorizer(lemmatized_data)
y = list_of_labels

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


refer to this website https://investigate.ai/text-analysis/counting-words-with-scikit-learns-countvectorizer/

In [244]:
#apply SVM machine learning algorithm
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)
from sklearn import svm 
svm = svm.SVC(kernel = 'linear', probability = True)
prob = svm.fit(X_train, y_train).predict_proba(X_test)
y_pred = svm.predict(X_test)

In [245]:
from sklearn.metrics import classification_report, confusion_matrix
y_pred_test = svm.predict(X_test)
CM = print(confusion_matrix(y_test, y_pred_test))

[[ 4  0 24]
 [ 1  6 13]
 [ 3  4 92]]


In [246]:
print(classification_report(y_test, y_pred_test))

              precision    recall  f1-score   support

           0       0.50      0.14      0.22        28
           1       0.60      0.30      0.40        20
           2       0.71      0.93      0.81        99

    accuracy                           0.69       147
   macro avg       0.60      0.46      0.48       147
weighted avg       0.66      0.69      0.64       147



# Climate Change is a Real Concern

In [263]:
target = 'Climate Change is a Real Concern'
df_target = df[df.Target == target]

df_target

Unnamed: 0                                              Tweet  \
613          613     We cant deny it, its really happening.  #SemST   
614          614  RT @cderworiz: Timelines are short. Strategy m...   
615          615  SO EXCITING! Meaningful climate change action ...   
616          616  Delivering good jobs for Albertans, maintainin...   
617          617  @davidswann says he wants carbon fund to be sp...   
...          ...                                                ...   
3298         384  @LiberalAus - "All" you folks #owe me an #offi...   
3299         385  Maybe we should start "labelling every #produc...   
3300         386  If we touch #Antarctica for one more #reason o...   
3301         387  Wind power helped stabilize Texas' power grid ...   
3302         388  It's so cold and windy here in Sydney, I just ...   

                                Target Stance  \
613   Climate Change is a Real Concern  FAVOR   
614   Climate Change is a Real Concern  FAVOR   
615   Climate Change is a Real Concern  FAVOR   
616   Climate Change is a Real Concern  FAVOR   
617   Climate Change is a Real Concern  FAVOR   
...                                ...    ...   
3298  Climate Change is a Real Concern   NONE   
3299  Climate Change is a Real Concern  FAVOR   
3300  Climate Change is a Real Concern  FAVOR   
3301  Climate Change is a Real Concern  FAVOR   
3302  Climate Change is a Real Concern  FAVOR   

                                        Opinion Towards Sentiment  
613   1.  The tweet explicitly expresses opinion abo...     other  
614   1.  The tweet explicitly expresses opinion abo...       pos  
615   1.  The tweet explicitly expresses opinion abo...       pos  
616   1.  The tweet explicitly expresses opinion abo...       pos  
617   3.  The tweet is not explicitly expressing opi...     other  
...                                                 ...       ...  
3298  3.  The tweet is not explicitly expressing opi...       neg  
3299  1.  The tweet explicitly expresses opinion abo...       pos  
3300  1.  The tweet explicitly expresses opinion abo...       neg  
3301  1.  The tweet explicitly expresses opinion abo...       pos  
3302  1.  The tweet explicitly expresses opinion abo...     other  

[564 rows x 6 columns]

In [264]:
df_target = df_target.drop('Unnamed: 0', axis='columns')
df_target = df_target.reset_index()
df_target = df_target.drop('index', axis='columns')

df_target

Tweet  \
0       We cant deny it, its really happening.  #SemST   
1    RT @cderworiz: Timelines are short. Strategy m...   
2    SO EXCITING! Meaningful climate change action ...   
3    Delivering good jobs for Albertans, maintainin...   
4    @davidswann says he wants carbon fund to be sp...   
..                                                 ...   
559  @LiberalAus - "All" you folks #owe me an #offi...   
560  Maybe we should start "labelling every #produc...   
561  If we touch #Antarctica for one more #reason o...   
562  Wind power helped stabilize Texas' power grid ...   
563  It's so cold and windy here in Sydney, I just ...   

                               Target Stance  \
0    Climate Change is a Real Concern  FAVOR   
1    Climate Change is a Real Concern  FAVOR   
2    Climate Change is a Real Concern  FAVOR   
3    Climate Change is a Real Concern  FAVOR   
4    Climate Change is a Real Concern  FAVOR   
..                                ...    ...   
559  Climate Change is a Real Concern   NONE   
560  Climate Change is a Real Concern  FAVOR   
561  Climate Change is a Real Concern  FAVOR   
562  Climate Change is a Real Concern  FAVOR   
563  Climate Change is a Real Concern  FAVOR   

                                       Opinion Towards Sentiment  
0    1.  The tweet explicitly expresses opinion abo...     other  
1    1.  The tweet explicitly expresses opinion abo...       pos  
2    1.  The tweet explicitly expresses opinion abo...       pos  
3    1.  The tweet explicitly expresses opinion abo...       pos  
4    3.  The tweet is not explicitly expressing opi...     other  
..                                                 ...       ...  
559  3.  The tweet is not explicitly expressing opi...       neg  
560  1.  The tweet explicitly expresses opinion abo...       pos  
561  1.  The tweet explicitly expresses opinion abo...       neg  
562  1.  The tweet explicitly expresses opinion abo...       pos  
563  1.  The tweet explicitly expresses opinion abo...     other  

[564 rows x 5 columns]

In [265]:
list_of_climate_tweets = []
for t in range(len(df_target)):
    list_of_climate_tweets.append(df_target['Tweet'][t])
list_of_climate_tweets

['We cant deny it, its really happening.  #SemST',
 'RT @cderworiz: Timelines are short. Strategy must be in place by climate change conference in Paris by December. #ableg #SemST',
 'SO EXCITING! Meaningful climate change action is on the way! #abpoli #GHG #SemST',
 'Delivering good jobs for Albertans, maintaining a stable economy & meeting climate change strategy. Good goals. #abpoli #GHG #SemST',
 '@davidswann says he wants carbon fund to be spent on public transportation and renewable energy. #ejlive #ableg #SemST',
 'Questions about the @LancetGH report?  #asklancet tweet chat happening now! #actonclimate #ClimateHealth #SemST',
 'We are working to elect climate-friendly governments across North America #FeelTheBern #NDP #LPC #GPC #BQ #HARPERPAC.CA #SemST',
 '@ChrisLeinberger :  change from #drivable to #walkable = #1 benefit 4 #APANE2015 #SemST',
 'Our amazing #ESS15 panel @gkremen, @SuffolkBuilds, @maxfieldweiss & @Oakland on how to prepare & protect #BayArea region from #SemST'

In [266]:
list_of_labels = []
for t in range(len(df_target)):
    if df_target['Stance'][t] == 'FAVOR':
        list_of_labels.append(1)
    elif df_target['Stance'][t] == 'AGAINST':
        list_of_labels.append(2)
    else:
        list_of_labels.append(0) 

In [267]:
list_of_labels

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 2,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 2,
 0,
 1,
 0,
 1,
 2,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,


In [268]:
pip install nltk

Defaulting to user installation because normal site-packages is not writeable
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))) - skipping
Note: you may need to restart the kernel to use updated packages.


In [269]:
import nltk

In [270]:
nltk.download('averaged_perceptron_tagger')

[nltk_data] Error loading averaged_perceptron_tagger: HTTP Error 401:
[nltk_data]     Unauthorized


False

In [271]:
# WORDNET LEMMATIZER (with appropriate pos tags)

from nltk.stem import WordNetLemmatizer
#nltk.download('averaged_perceptron_tagger')
from nltk.corpus import wordnet
from nltk.corpus import stopwords

nltk.download('stopwords')

[nltk_data] Error loading stopwords: HTTP Error 401: Unauthorized


False

In [272]:
 
lemmatizer = WordNetLemmatizer()
 
# Define function to lemmatize each word with its POS tag
 
# POS_TAGGER_FUNCTION : TYPE 1
def pos_tagger(nltk_tag):
    if nltk_tag.startswith('J'):
        return wordnet.ADJ
    elif nltk_tag.startswith('V'):
        return wordnet.VERB
    elif nltk_tag.startswith('N'):
        return wordnet.NOUN
    elif nltk_tag.startswith('R'):
        return wordnet.ADV
    else:         
        return None
 
def lemmatizing(data):
    lemmatized_data = []
    for i in range(len(data)):
        sentence = data[i]

        # tokenize the sentence and find the POS tag for each token
        word_tokens = nltk.wordpunct_tokenize(sentence)
 
        pos_tagged = nltk.pos_tag(word_tokens) 

        
        # As you may have noticed, the above pos tags are a little confusing.
        
        # we use our own pos_tagger function to make things simpler to understand.
        wordnet_tagged = list(map(lambda x: (x[0], pos_tagger(x[1])), pos_tagged))
        
        lemmatized_sentence = []
        for word, tag in wordnet_tagged:
            if tag is None:
                # if there is no available tag, append the token as is
                lemmatized_sentence.append(word)
            else:       
                # else use the tag to lemmatize the token
                lemmatized_sentence.append(lemmatizer.lemmatize(word, tag))
        lemmatized_sentence = " ".join(lemmatized_sentence)
        lemmatized_data.append(lemmatized_sentence)
    return lemmatized_data

In [273]:
#CountVectorizer
def count_vectorizer(list):
    vectorizer = CountVectorizer(stop_words= 'english', lowercase=True, ngram_range=(1,3))
    matrix = vectorizer.fit_transform(list)
    count_table = pd.DataFrame(matrix.toarray(), columns=vectorizer.get_feature_names())
    return matrix, count_table

In [274]:
os.environ['NLTK_DATA']

'C:/Users/13630/Desktop/NLTK_datasets/corpora'

In [275]:
import os
os.environ['NLTK_DATA'] = str('C:/Users/13630/Desktop/NLTK_datasets/corpora')
lemmatized_data = lemmatizing(list_of_climate_tweets)
X, count_table = count_vectorizer(lemmatized_data)
y = list_of_labels

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


refer to this website https://investigate.ai/text-analysis/counting-words-with-scikit-learns-countvectorizer/

In [276]:
#apply SVM machine learning algorithm
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)
from sklearn import svm 
svm = svm.SVC(kernel = 'linear', probability = True)
prob = svm.fit(X_train, y_train).predict_proba(X_test)
y_pred = svm.predict(X_test)

In [277]:
from sklearn.metrics import classification_report, confusion_matrix
y_pred_test = svm.predict(X_test)
CM = print(confusion_matrix(y_test, y_pred_test))

[[30 13  0]
 [13 52  0]
 [ 2  2  1]]


In [278]:
print(classification_report(y_test, y_pred_test))

              precision    recall  f1-score   support

           0       0.67      0.70      0.68        43
           1       0.78      0.80      0.79        65
           2       1.00      0.20      0.33         5

    accuracy                           0.73       113
   macro avg       0.81      0.57      0.60       113
weighted avg       0.74      0.73      0.73       113

